/* ===================== CLUES + ITEMS ===================== */
const CLUES = {
  ransom: { name: 'Ransom Note', short: 'Ransom', icon: 'note', desc: 'Letters cut from a Buenos Aires newspaper: "WE HAVE YOUR QB. $20 MILLION OR HE THROWS FOR THE OTHER TEAM. PERMANENTLY." The glue smells like Malbec.' },
  dutyfree: { name: 'Duty-Free Receipt', short: 'Receipt', icon: 'receipt', desc: 'Buenos Aires Ezeiza duty free, 2 days ago: one Malbec, one tango-shoe keychain, and "1x GLUE STICK, INDUSTRIAL." Somebody flew in just to drop this.' },
  chadstream: { name: 'HogWildChad Livestream', short: 'Stream', icon: 'phone', desc: 'Frame 4,402 of Chad\'s stream: a cleaning cart, and a hand with a two-headed pig tattoo on the wrist. Chad says it\'s "a fan." Chad has no fans.' },
  coin: { name: 'The Siamese Swine', short: 'Coin', icon: 'coin', desc: 'A gold coin with a pig on BOTH sides, joined at the rim like Siamese twins. Heads they lose. Tails they lose. A calling card.' },
  carnation: { name: 'Red Carnation', short: 'Carnation', icon: 'scarf', desc: 'La Viuda\'s signature flower. Pinned to it: a milonga ticket stub with "R.J. 2am" in lipstick.' },
  milongaphoto: { name: 'Milonga Photo', short: 'Photo', icon: 'photo', desc: 'Ringo, tangoing badly, with a thin man in a pencil mustache: Tito Ferraro, bandoneón player, bookie, and owner of zero rhythm.' },
  bandoneon: { name: 'Bandoneón Sheet Music', short: 'Music', icon: 'note', desc: 'Tito\'s music. The notes don\'t make a melody. They make coordinates: 54.8°S, 68.3°W. Ushuaia. The end of the world.' },
  footprint: { name: 'Bloody Hog Sneaker Print', short: 'Print', icon: 'print', desc: 'Size 13 Razorback-branded sneaker print, in blood, walking AWAY from the body. Who wears team merch to a murder? A superfan.' },
  titophone: { name: 'Tito\'s Phone', short: 'Tito Phone', icon: 'phone', desc: 'Last text, from "CRAB DADDY 🦀": "Package is in the tank. Stop calling me, Tito." Package. Tank. Oh no.' },
  crabchip: { name: 'Lotus Palace Chip', short: 'Chip', icon: 'chip', desc: 'A $10,000 chip from the Lotus Palace Casino, Macau, found in Ringo\'s sock. Somebody paid him. He didn\'t spend it.' },
  nilcontract: { name: 'Fake NIL Contract', short: 'NIL Deal', icon: 'ledger', desc: '"Vauclair Talent, Monaco." $2M for Ringo to "endorse luxury yachts." Clause 9: "Athlete agrees to lose on purpose (vibes-wise)."' },
  ringowatch: { name: 'Ringo\'s Watch', short: 'Watch', icon: 'watch', desc: 'Stopped at 3:12 AM, the night he "went missing." He was never kidnapped. He was dead before the ransom note hit XNA.' },
  brockcam: { name: 'Brock\'s GoPro', short: 'GoPro', icon: 'drive', desc: 'Footage from the Death Road: Brock handing a duffel bag of cash to a man on Easter Island\'s ferry. Label: "KRILL - MOAI MONEY."' },
  wire: { name: 'Wire Transfer Slip', short: 'Wire', icon: 'receipt', desc: '$400,000, La Paz to "Saffron Queen Imports, Marrakech." Memo line: "for the spice ;)"' },
  feather: { name: 'Sooty Tern Feather', short: 'Feather', icon: 'feather', desc: 'Birdman race token, stained with ink: "THE COUNT PAYS IN MONACO. BRING THE EGG." The egg is a USB drive. Of course it is.' },
  moaiusb: { name: 'Egg-Shaped USB', short: 'USB Egg', icon: 'drive', desc: 'Inside: payroll for "Vauclair Talent" going back TWENTY YEARS. The Hogs didn\'t just lose. Somebody made them lose.' },
  saffron: { name: 'Saffron Ledger', short: 'Saffron', icon: 'ledger', desc: 'Zohra\'s books: every shipment of saffron is a payout. Biggest buyer: a yacht in Monaco called "THE POINT SPREAD."' },
  yachtcard: { name: 'Yacht Keycard', short: 'Keycard', icon: 'card', desc: '"THE POINT SPREAD, Monaco. VIP." A keycard for the Count\'s yacht.' },
  golfball: { name: 'Bloody Golf Ball', short: 'Golf Ball', icon: 'coin', desc: 'Monogrammed "C de V." Found in the hot tub. The Count plays golf. The Count does not play well with others.' },
  yachttape: { name: 'Yacht Security Tape', short: 'Tape', icon: 'tape', desc: 'Grainy footage: a man in a hog-snout hat leaving the hot tub deck at 1:04 AM. He waves at the camera. He would.' },
  toast: { name: 'Zurab\'s Toast', short: 'Toast', icon: 'glass', desc: '"To two brothers who share one liver, one desk, and one pen. They write the papers. They drink to our health." Siamese-twin forgers? In Siem Reap?' },
  winelabel: { name: 'Wine Label Code', short: 'Label', icon: 'bottle', desc: 'A Georgian amber wine label with a bank routing number hidden in the vintage. The Banker banks in wine.' },
  bjarkiglasses: { name: 'Fogged Glasses', short: 'Glasses', icon: 'glass', desc: 'Bjarki\'s round glasses, cracked. Etched inside the lens: "THE CLEANER HAS A CAMERA." A camera? A gimbal?' },
  drawing: { name: 'KD\'s Drawing', short: 'KD Art', icon: 'drawing', desc: 'KD drew "the air man" from the plane: hog hat, gimbal, and a two-headed pig tattoo on his wrist. It is the single best piece of evidence in this case. It\'s in crayon.', proof: 1 },
  ledger: { name: 'The Master Ledger', short: 'Ledger', icon: 'ledger', desc: 'Twenty years of payoffs. Every page initialed "B.P. - COMMISSIONER." Every loss, every bribe, every body.', proof: 1 },
  tracker: { name: 'Keychain Tracker', short: 'Tracker', icon: 'tracker', desc: 'Inside KD\'s light-up Hog keychain: a GPS tracker registered to "Pettigrew\'s Hog Heaven Catfish LLC." He\'s been following us since XNA.', proof: 1 },
  tankphoto: { name: 'Tank\'s Phone Pics', short: 'Tank Pics', icon: 'photo', desc: 'Tank Dobbins on a dhow, holding Ringo\'s jersey like a trophy, with Chad. Chad is doing a peace sign. At a crime.', proof: 1 },
  hawkecontract: { name: 'Forged Contracts', short: 'Forgeries', icon: 'ledger', desc: 'The Hawke twins\' forgeries: one twin wrote the contracts, the other signed them. Signed for "The Commissioner" by "B."' },
  lautape: { name: 'Lau\'s Recording', short: 'Lau Tape', icon: 'tape', desc: 'Madame Lau taped every call. On this one, a sweet old Southern voice: "Ringo won\'t play ball. Have Chad clean it up, darlin\'."', proof: 1 },
  cane: { name: 'Hog-Head Cane', short: 'Cane', icon: 'cane', desc: 'Pettigrew\'s cane. The hog head twists off. Inside: a hollow chamber that smells like gunpowder and old money.', proof: 1 },
  casing: { name: '.41 Derringer Casing', short: 'Casing', icon: 'bullet', desc: 'From the suite floor. A .41 rimfire, the kind fired by an antique derringer, the kind that fits inside a hog-head cane.', proof: 1 },
  chadsticker: { name: 'Chad\'s Sticker', short: 'Sticker', icon: 'card', desc: '"HOGWILDCHAD: SMASH THAT SUBSCRIBE." Found at every crime scene. Subscribers: 1,212. Suspects: 1.' },
};
const ITEMS = {
  malbec: { name: 'Malbec (Big Bottle)', ic: '🍷', tags: ['booze'], desc: 'Argentine red. Liquid courage, liquid bribe.' },
  cookies: { name: 'Gigi\'s Cookie Tin', ic: '🍪', tags: ['sweet', 'booze', 'jewel', 'cash', 'food', 'fashion', 'sports'], desc: 'Nobody can resist. Nobody.' },
  jersey: { name: 'Signed Hogs Jersey', ic: '🏈', tags: ['sports'], desc: 'Ringo\'s #7. Priceless. Use wisely.' },
  saffronjar: { name: 'Saffron Jar', ic: '🌺', tags: ['food', 'jewel'], desc: 'Worth more than gold by weight.' },
  tanzanite: { name: 'Tanzanite Ring', ic: '💍', tags: ['jewel', 'fashion'], desc: 'Blue. Kayleigh\'s color. Almost too pretty to bribe with.' },
  cigar: { name: 'Fancy Cigars', ic: '🚬', tags: ['vice'], desc: 'For men who say "between you and me."' },
  chacha: { name: 'Chacha (Grape Moonshine)', ic: '🥃', tags: ['booze'], desc: 'Georgian rocket fuel.' },
  hogcap: { name: 'Hog Snout Cap', ic: '🐗', tags: ['sports', 'fashion'], desc: 'Universally recognized symbol of poor choices.' },
  eggtarts: { name: 'Egg Tarts', ic: '🥧', tags: ['food', 'sweet'], desc: 'KD ate fourteen. These survived.' },
  chips: { name: 'Casino Chips', ic: '🎰', tags: ['cash', 'vice'], desc: '$5,000 in chips. Technically evidence.' },
};
