/* ===================== CHAPTERS 1-6 ===================== */
const CH = [];
CH.push({ id: 'xna', n: 1, title: 'Fly Away Home', city: 'Fayetteville, Arkansas · XNA', bg: 'xna', music: 'noir', party: { kd: 1, cocoa: 1, kambree: 0 }, hours: 672,
  tag: 'A spring-break flight. A paint can of coffee. A feeling.',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'kd', 'cocoa'] },
      ['n', 'Northwest Arkansas. Home of the Razorbacks, the most loyal fans in college football, God help us. And at 6:10 on a Saturday morning, home of me: a mom with a vacation, a paint can of coffee, and a feeling.'],
      ['*', 'On the gate TV, Coach Duke Barlow sweats through a press conference. Star QB Ringo Jones hasn\'t been seen since Thursday.'],
      ['kay', 'He\'s been gone two days and the coach is calling it "me-time." Babe, that\'s how every true-crime episode starts.', 'smirk'],
      ['kd', 'Mommy, is that man\'s hat a NOSE?', 'grin'],
      { on: ['kay', 'chad', 'kd'] },
      ['chad', 'What\'s up, Hog Nation! HogWildChad, LIVE from XNA! Twelve hundred subscribers, let\'s GOOO!', 'grin'],
      ['kay', 'Don\'t make eye contact with the pig man, baby.', 'smirk'],
      { on: ['kay', 'cocoa', 'kd'] },
      ['*', 'Cocoa stands up. Ears forward. She drags Kayleigh, coffee and all, toward a cleaning cart by the jet bridge.'],
      ['kay', 'Cocoa! Drop it. That\'s garbage, baby, that\'s... oh. Oh, that\'s a ransom note.', 'shock'],
      { card: { kind: 'note', title: 'WE HAVE YOUR QB', text: 'RINGO JONES IS OURS.\n$20,000,000 OR HE THROWS FOR THE OTHER TEAM.\nPERMANENTLY.\nTELL NO COPS. TELL NO COACHES.\n(THE COACH WOULDN\'T NOTICE ANYWAY)', font: 'marker', px: 18, col: '#9d1c2a', h: 280 }, sfx: 'page' },
      { clue: 'ransom' },
      ['kay', 'Okay. Okay. Tutorial time, Kayleigh: look around before somebody vacuums the evidence.', 'neutral'],
    ] },
    { t: 'invest', title: 'GATE A3', bg: 'xna', intro: 'Tap anything suspicious. Cocoa\'s SNIFF lights up what she smells.', sites: [{ id: 'gate', name: 'Gate A3', clues: [{ id: 'dutyfree', x: .22, y: .78 }, { id: 'chadstream', x: .78, y: .58 }], jokes: [{ icon: 'cigar', x: .55, y: .86, who: 'kay', say: 'A half-eaten corn dog. At 6 AM. Arkansas, I love you.' }] }] },
    { t: 'interro', id: 'chad', intro: 1 },
    { t: 'story', s: [{ on: ['kay', 'pettigrew', 'kd'] },
      ['*', 'A sweet old man in a white suit taps Kayleigh\'s shoulder. Hog-head cane. Bow tie. A laugh like a church bell.'],
      ['pettigrew', 'Darlin\', I heard you on the phone. Bo Pettigrew. Pettigrew\'s Hog Heaven Catfish? Nobody else is gonna go get our boy. I\'ll cover every dime.', 'smile'],
      ['kay', 'Sir, I\'m a mom with a podcast habit, not a cop.', 'smile'],
      ['pettigrew', 'Exactly why they won\'t see you comin\'. And for the little man... a light-up Hog keychain. For luck.', 'smile'],
      ['kd', 'IT BLINKS! Thank you, Mister Ice Cream Suit!', 'grin'],
      { item: 'hogcap' },
      ['n', 'The note smelled like Malbec and glue. The receipt said Buenos Aires. My flight to Orlando said "boarding." I said a word KD charged me a dollar for.'],
      ['kay', 'Shit.', 'smirk'],
      ['kd', 'SWEAR JAR!', 'grin'],
      ['kay', 'Put it on my tab, baby. We\'re going to Argentina.', 'grin'],
      { on: ['kay'] },
      { card: { kind: 'text', from: 'KAMBREE 🎀 (baby sis)', text: 'u found a WHAT at the airport?? do NOT go to argentina with a 6 yr old and a dog. ...ok fine. i\'m FBI legal attaché in BA, I\'ll meet you. bring me a hello kitty keychain from the airport or i\'ll arrest you myself', h: 220 } },
    ] },
    { t: 'game', kind: 'chase', id: 'xna_run', vehicle: 'foot', bg: 'xna', road: '#4a4256', side: '#2a2436', stripe: '#9a90b0', obs: ['crate', 'cone', 'barrel'], dur: 20, target: 'GATE B7', targetV: 'foot', targetCol: '#ffd23a', title: 'Run for the Gate', how: 'Final boarding call for Atlanta → Buenos Aires! Tap LEFT or RIGHT to dodge luggage carts and wet-floor signs. Grab cash.', win: 'Made it. KD is asleep before takeoff. Cocoa snores like a leaf blower.', lose: 'You took out a Hudson News display. KD is applauding.' },
    { t: 'flight', from: 'XNA · Northwest Arkansas', q: 'The receipt and the newspaper letters point to one city. Where to?', hint: 'Check the duty-free receipt.', dest: 'BUENOS AIRES', opts: [{ code: 'MCO', city: 'Orlando (vacation)', no: 'KD: "Mickey can wait, Mommy. Ringo can\'t." Out of the mouths of babes.' }, { code: 'EZE', city: 'Buenos Aires', ok: 1 }, { code: 'LIT', city: 'Little Rock', no: 'Nobody gets kidnapped TO Little Rock. Not even Little Rock people.' }, { code: 'CUN', city: 'Cancún', no: 'That\'s spring break, not a crime scene. ...Usually.' }] },
  ] });

CH.push({ id: 'ba1', n: 2, title: 'Don\'t Cry for Me, Arkansas', city: 'Buenos Aires, Argentina', bg: 'ba', music: 'noir', party: { kd: 1, cocoa: 1, kambree: 0 }, tag: 'Dinner at 11 PM. Tango at 2 AM. Lies all night.',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'kd', 'cocoa'], bg: 'ba' },
      ['n', 'Buenos Aires at midnight smelled like grilled beef, cheap perfume and a lie. I\'d know. I\'ve told all three.'],
      ['kd', 'Mommy, why is everybody eating dinner at bedtime?', 'grin'],
      ['kay', 'Because Argentina is cooler than us, baby. Eat your empanada.', 'smile'],
      { card: { kind: 'text', from: 'KAMBREE 🎀', text: 'stuck in a meeting with 6 men named Gustavo. the ransom paper is from a BA newspaper. ringo was seen at a milonga in san telmo. go dance, dork. DON\'T get stabbed. if you get stabbed i\'m wearing your blue jacket to the funeral', h: 220 } },
      ['kay', 'My sister, everybody. Joined at the hip like Siamese twins, except I\'m the pretty one.', 'grin'],
    ] },
    { t: 'invest', title: 'SAN TELMO MILONGA', bg: 'milonga', intro: 'Three spots in the dance hall. Each search costs a couple of hours.', sites: [
      { id: 'bar', name: 'The Bar', icon: '🍷', hours: 2, clues: [{ id: 'carnation', x: .3, y: .7 }], jokes: [{ icon: 'bottle', x: .7, y: .8, who: 'kay', say: 'Malbec, Malbec, Malbec... and one bottle of ranch dressing. An American was here.' }] },
      { id: 'floor', name: 'Dance Floor', icon: '💃', hours: 2, clues: [{ id: 'milongaphoto', x: .65, y: .62 }] },
      { id: 'back', name: 'Back Room', icon: '🚪', hours: 3, clues: [{ id: 'coin', x: .45, y: .75 }], jokes: [{ icon: 'cigar', x: .2, y: .6, who: 'kd', say: 'This room smells like Grandpa\'s truck.' }] },
    ], need: 2 },
    { t: 'story', s: [{ on: ['kay', 'viuda'] },
      ['*', 'A woman in black and red glides across the floor like the music owes her money. La Viuda. Four husbands. Zero still breathing.'],
      ['viuda', 'Americana. You dance? No? Then why are you in my milonga with a child and a dog?', 'smug'],
      ['kay', 'The child\'s asleep in the coat check with the dog. I\'m here about Ringo Jones.', 'neutral'],
      ['viuda', 'Dance with me first. Then we talk. Maybe.', 'smug'],
    ] },
    { t: 'game', kind: 'rhythm', id: 'tango', bg: 'milonga', cast: ['kay', 'viuda'], bpm: 100, n: 14, need: 9, glyph: '♥', title: 'Tango Interrogation', how: 'Tap when each heart hits the ring. Don\'t step on her feet. Lead like you mean it.', win: 'La Viuda: "Okay. You can dance. Badly, but with confidence. Like an American."', lose: 'You stepped on her foot. Twice. She is not amused.' },
    { t: 'interro', id: 'viuda' },
    { t: 'board', title: 'CONNECT THE DOTS', qs: [{ q: 'Who did Ringo leave the milonga with?', opts: ['La Viuda', 'Tito Ferraro, the bandoneón player', 'HogWildChad', 'Coach Barlow'], a: 1, yes: 'The milonga photo. Pencil mustache. Tito Ferraro.', no: 'Wrong. Look at the photo again.' }, { q: 'What is the Siamese Swine?', opts: ['A pork dish', 'The Spread\'s calling card: a pig on both sides', 'Gigi\'s cats', 'A wrestling move'], a: 1, yes: 'Heads they lose. Tails they lose. Joined at the rim.' }] },
    { t: 'story', s: [{ on: ['kay', 'kd', 'cocoa'] },
      ['n', 'The widow had danced me straight to the truth: Ringo said no to somebody\'s money. And Tito Ferraro took him to a cemetery at dawn. I\'ve seen enough documentaries to know how that ends.'],
      ['kd', 'Mommy, are we going to the cemetery? Can I bring my juice?', 'grin'],
      ['kay', 'You and Cocoa are going to the hotel with the nice concierge lady and a whole pile of dulce de leche.', 'smile'],
    ] },
  ] });

CH.push({ id: 'ba2', n: 3, title: 'Recoleta at Dawn', city: 'Buenos Aires · Recoleta Cemetery', bg: 'recoleta', music: 'noir', party: { kd: 0, cocoa: 0, kambree: 0 }, tag: 'The dead have the best real estate in Buenos Aires.',
  steps: [
    { t: 'story', s: [{ on: ['kay'], bg: 'recoleta' },
      ['n', 'Recoleta Cemetery. Marble angels, sleeping cats, and the most expensive dead people in South America. At dawn the fog hangs between the tombs like it\'s waiting for a cue.'],
      ['*', 'A bandoneón wheezes one long note somewhere in the rows... then stops.'],
      ['kay', 'That\'s not a good stop. That\'s a murder stop.', 'shock'],
    ] },
    { t: 'invest', crime: 'tito', title: 'CRIME SCENE: TITO FERRARO', bg: 'recoleta', sites: [{ id: 'tomb', name: 'Crime Scene · Tomb Row 7', clues: [{ id: 'bandoneon', x: .78, y: .55 }, { id: 'footprint', x: .2, y: .9 }, { id: 'titophone', x: .12, y: .45 }] }],
      autopsy: V('Throat opened ear to ear, left to right, one confident stroke: a right-handed killer standing behind him. The cut went deep enough to nick the spine. He bled out over his own bandoneón in under a minute; you can see where the bellows sucked blood into the pleats on its last wheeze. A gold coin was pushed into his mouth after death. A cemetery cat has been licking his fingers. Nobody has stopped it.', 'A single wound to the neck; it was quick. A gold coin was placed in his mouth afterward. A cemetery cat is sitting with him, which is honestly sweet.') },
    { t: 'story', s: [{ on: ['kay'] },
      { card: { kind: 'postcard', title: 'Meanwhile, KD...', text: 'KD has taught the hotel concierge, Señora Paz, the Hog Call. She has taught KD to say "dulce de leche" correctly. Cocoa has eaten a croissant off a businessman\'s plate. Everyone is happy except the businessman.', font: 'marker', px: 16, h: 250 } },
      ['n', 'A sneaker print walked away from the body. Size 13. Hog logo. The killer wore team merch to a murder. Superfan behavior.'],
      ['*', 'A shape in a snout hat bolts between the mausoleums.'],
      ['kay', 'HEY! Pig hat! Freeze!', 'angry'],
    ] },
    { t: 'game', kind: 'chase', id: 'recoleta_run', vehicle: 'foot', bg: 'recoleta', road: '#8a8270', side: '#3a3a30', stripe: '#c8c0a8', obs: ['crate', 'rock', 'barrel'], dur: 22, target: 'PIG HAT', targetV: 'foot', targetCol: '#9d1c2a', title: 'Chase Through the Tombs', how: 'Dodge tombstones, cats and a very confused tour group. Tap LEFT/RIGHT.', win: 'You grab his jacket... and he slips out of it like a snake. Gone. But you got a whiff: Malbec and glue.', lose: 'You tripped over a cat. The cat is fine. Your dignity is buried in Recoleta.' },
    { t: 'board', qs: [{ q: 'Where did Tito\'s sheet music point?', opts: ['Montevideo', 'Ushuaia: the end of the world', 'Mendoza wine country', 'Disney World'], a: 1, yes: '54.8°S, 68.3°W. Ushuaia.' }, { q: 'Who texted Tito "Package is in the tank"?', opts: ['La Viuda', 'Crab Daddy', 'Bo Pettigrew', 'Señora Paz'], a: 1, yes: 'Crab Daddy 🦀. Of course a man named Crab Daddy owns a tank.' }] },
    { t: 'flight', from: 'AEP · Buenos Aires', q: 'Tito\'s sheet music + "Package is in the tank." Where next?', dest: 'USHUAIA', opts: [{ code: 'USH', city: 'Ushuaia, Tierra del Fuego', ok: 1 }, { code: 'MDZ', city: 'Mendoza', no: 'Wine country is a vibe, but the coordinates say end of the world.' }, { code: 'IGR', city: 'Iguazú Falls', no: 'Gorgeous. Wrong. Six hours you\'ll never get back.' }] },
  ] });

CH.push({ id: 'ushuaia', n: 4, title: 'The End of the World', city: 'Ushuaia, Argentina', bg: 'ushuaia', music: 'interro', party: { kd: 0, cocoa: 1, kambree: 0 }, tag: 'Southernmost city on Earth. Northernmost bad decisions.',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'cocoa'], bg: 'ushuaia' },
      ['n', 'Ushuaia. The last city before Antarctica. Snow on the mountains, crab boats in the harbor, and a tank I didn\'t want to look into.'],
      { card: { kind: 'postcard', title: 'Meanwhile, KD...', text: 'KD is on the penguin boat with Señora Paz\'s nephew Mateo and twelve retirees from Ohio. He has named every penguin "Gary." Mateo says he\'s never seen penguins listen to anyone like that.', font: 'marker', px: 16, h: 240 } },
      ['kay', 'Cocoa, find it. Find the tank.', 'neutral'],
    ] },
    { t: 'invest', crime: 'ringo', title: 'CRIME SCENE: THE CRAB TANK', bg: 'crabshack', sites: [{ id: 'tank', name: 'Crime Scene · Crab Daddy\'s Tank', clues: [{ id: 'crabchip', x: .2, y: .82 }, { id: 'ringowatch', x: .82, y: .8 }, { id: 'chadsticker', x: .5, y: .92 }] }],
      autopsy: V('Ringo Jones, 21. He was never kidnapped. Dead two days before the ransom note: single gunshot, back of the head, close range, powder tattooing on the scalp. The near-freezing water kept him "fresh," which is why the king crabs got patient. They took the soft parts first: lips, eyelids, fingertips. Fingertips. Somebody wanted him hard to identify. The jersey still says #7.', 'Ringo Jones, 21. He was never kidnapped; he died two days before the ransom note was found, from a single gunshot. The cold water preserved him. His #7 jersey was still on.') },
    { t: 'story', s: [{ on: ['kay', 'cocoa'] }, { music: 'noir' },
      ['n', 'It was never a kidnapping. The ransom note was theater. Ringo was dead before KD finished his gummy worms at XNA. Somebody wanted the whole world to look the wrong way.'],
      ['kay', 'Twenty-one. He was twenty-one. I\'m gonna find every one of you sons of bitches.', 'angry'],
      { on: ['kay', 'kambree', 'cocoa'], sfx: 'thud' },
      ['kambree', 'Well, well. Mom always said you\'d end up at the end of the world. She meant it as a threat.', 'angry'],
      ['kay', 'KAMBREE! You came!', 'grin'],
      ['kambree', 'Yeah, I came. Three flights, a turboprop, and a guy next to me who ate tuna out of a can with his fingers. I\'m in a mood, Kay. I\'m in THE mood.', 'angry'],
      ['kambree', 'Bureau says a homicide of a U.S. citizen means me. And since you\'re already six steps ahead of every swinging dick in D.C.... raise your right hand.', 'smug'],
      ['kay', 'Wait, for real?', 'shock'],
      ['kambree', 'Do you solemnly swear to support and defend, blah blah, and never touch my Mochi Meow stuff? Say "I do," dork.', 'smug'],
      ['kay', 'I do.', 'grin'],
      { set: { sworn: 1, noir: 1 }, party: { kambree: 1 }, toast: 'KAYLEIGH IS SWORN IN · NOIR TRENCH UNLOCKED', sfx: 'win', outfit: 'noir' },
      ['kambree', 'Congrats, you\'re a temporary special agent. Here\'s your badge. And here\'s a trench and a fedora, because if you\'re gonna do noir, you do it RIGHT. Navy, obviously. You\'ve worn blue since kindergarten.', 'smile'],
      ['kambree', 'And THIS is for the dog. "K-9 CONSULTANT." She gets a vest. You get a vest. Everybody gets a vest except the dead guy.', 'grin'],
      ['kay', 'Joined at the hip like Siamese twins, except I\'m the pretty one.', 'grin'],
      ['kambree', 'And I\'m the one with the gun. Now let\'s go ruin a crab man\'s whole day.', 'grin'],
    ] },
    { t: 'interro', id: 'crab' },
    { t: 'board', qs: [{ q: 'Why was Ringo killed?', opts: ['Gambling debts', 'He refused money to lose games', 'A tango dispute', 'He was dating a crab'], a: 1, yes: 'He said no. That\'s why. The fake NIL contract proves it.' }, { q: 'Where does the NIL money come from?', opts: ['Vauclair Talent, Monaco', 'Gigi\'s cookie fund', 'Coach Barlow\'s 401k', 'The Hog Heaven Catfish chain'], a: 0, yes: 'Monaco. But you don\'t get to Monaco by asking nicely. You follow the money down.' }] },
    { t: 'story', s: [{ on: ['kay', 'kambree', 'cocoa'] },
      ['kambree', 'Crab Daddy says the cash runs through a bike tour bro in La Paz. Pick up the brat from the penguins. We\'re going UP.', 'angry'],
      ['kay', 'Don\'t call my son a brat.', 'angry'],
      ['kambree', 'He named a penguin after me, Kay. He named it "Angry Gary."', 'angry'],
      { party: { kd: 1 } },
    ] },
    { t: 'flight', from: 'USH · Ushuaia', q: 'Crab Daddy: "the cash goes to a bike tour bro." Which city has the world\'s most dangerous bike road?', dest: 'LA PAZ', opts: [{ code: 'SCL', city: 'Santiago, Chile', no: 'Kambree: "Santiago? Is that where you keep your brain? WRONG."' }, { code: 'LPB', city: 'La Paz, Bolivia', ok: 1 }, { code: 'LIM', city: 'Lima, Peru', no: 'Great ceviche. Zero death roads.' }] },
  ] });

CH.push({ id: 'lapaz', n: 5, title: 'Death Road Bros', city: 'La Paz, Bolivia', bg: 'lapaz', music: 'travel', party: { kd: 1, cocoa: 1, kambree: 1 }, tag: '3,640 meters up. Oxygen optional. Bros mandatory.',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'kambree', 'kd'], bg: 'lapaz' },
      ['n', 'La Paz sits so high that the air is basically a rumor. Cable cars glide over the city like ski lifts to heaven. KD wants to ride all ten lines. Kambree wants to throw up off all ten lines.'],
      ['kambree', 'I can\'t breathe, Kay. I\'m gonna die up here and the last thing I\'ll see is your stupid trench coat.', 'angry'],
      ['kd', 'Aunt Kambree, you can have my juice box. It has oxygen in it.', 'grin'],
      ['kambree', '...Okay, that\'s actually sweet. You\'re my favorite. Don\'t tell your mom. She knows.', 'smile'],
      ['kay', 'Brock Dunleavy. Death Road Bros tours. Let\'s go meet a man who wears sunglasses on his forehead.', 'smirk'],
    ] },
    { t: 'invest', title: 'DEATH ROAD BROS HQ', bg: 'lapaz', sites: [{ id: 'shop', name: 'Bike Shop', icon: '🚲', hours: 2, clues: [{ id: 'brockcam', x: .3, y: .75 }], jokes: [{ icon: 'bottle', x: .75, y: .8, who: 'kambree', say: 'Forty empty energy drinks. This man\'s heart sounds like a dubstep remix.' }] }, { id: 'desk', name: 'Front Desk', icon: '🗂', hours: 2, clues: [{ id: 'wire', x: .7, y: .7 }] }] },
    { t: 'story', s: [{ on: ['kay', 'brock'] }, ['brock', 'Yo! Death Road Bros! You here for the tour? It\'s sick. Some people die but like, the cool ones survive.', 'grin'], ['kay', 'Brock, I\'m FBI. Don\'t run.', 'neutral'], ['brock', '...', 'scared'], ['*', 'Brock runs. Brock grabs a mountain bike. Brock goes down the Death Road.'], ['kambree', 'He ran. Oh, he RAN. Kay, get on a bike. KD, you stay with the nice cholita lady and Cocoa.', 'angry'] ] },
    { t: 'game', kind: 'chase', id: 'deathroad', vehicle: 'bike', bg: 'lapaz', road: '#8a6a4a', side: '#3a6a3a', stripe: '#c8a878', obs: ['rock', 'llama', 'cone', 'rock'], dur: 30, target: 'BROCK', targetV: 'bike', targetCol: '#1fbf8a', title: 'Death Road Chase', how: 'Downhill. No guardrails. One llama. Tap LEFT/RIGHT to dodge and stay on Brock.', win: 'Brock wipes out into a pile of llama blankets. He is fine. He is crying, but fine.', lose: 'You went off the road into a bush. The llama spat on you. Kambree is laughing so hard she sat down.' },
    { t: 'interro', id: 'brock' },
    { t: 'story', s: [{ on: ['kay', 'tormenta', 'kd'] },
      { card: { kind: 'postcard', title: 'Meanwhile, KD...', text: 'KD watched cholitas lucha libre in El Alto with La Tormenta Dorada, a wrestler in a bowler hat and a golden skirt who can bodyslam a man twice her size. She taught KD her signature move: The Grandma Hug. He used it on Cocoa. Cocoa won.', font: 'marker', px: 15, h: 260 } },
      ['tormenta', 'Your boy is a champion, señora. And YOU, you look like you want to wrestle.', 'grin'],
      ['kay', 'I mean... I\'ve had a week.', 'smirk'],
    ] },
    { t: 'game', kind: 'rhythm', id: 'cholita', bg: 'lapaz', cast: ['kay', 'tormenta'], bpm: 112, n: 12, need: 7, glyph: '✊', title: 'Cholita Wrestling Exhibition', how: 'La Tormenta wants a friendly bout. Tap on the beat to block, spin and flip. Skirts will twirl.', win: 'The crowd goes WILD. La Tormenta lifts you up like a trophy. KD has never been prouder.', lose: 'She pinned you with one hand while waving to the crowd with the other. Respect.', item: 'malbec' },
    { t: 'flight', from: 'LPB · La Paz', q: 'Brock: "Dr. Krill hides it in a moai." Where are the moai?', dest: 'EASTER ISLAND', opts: [{ code: 'IPC', city: 'Easter Island (Rapa Nui)', ok: 1 }, { code: 'PPT', city: 'Tahiti', no: 'Pretty! Wrong. Kambree bought a coconut bra out of spite.' }, { code: 'GPS', city: 'Galápagos', no: 'Turtles, not moai. KD is devastated anyway.' }] },
  ] });

CH.push({ id: 'easter', n: 6, title: 'Birdman', city: 'Rapa Nui (Easter Island), Chile', bg: 'easter', music: 'travel', party: { kd: 1, cocoa: 1, kambree: 1 }, tag: 'The most remote inhabited island on Earth. Great place to hide money. Terrible place to hide from Kambree.',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'kambree', 'kd'], bg: 'easter' },
      ['n', 'Rapa Nui. Nearly a thousand moai stand with their backs to the sea, watching over their people. One of them was watching over a whole lot of dirty money.'],
      ['kd', 'Mommy, they look like Aunt Kambree when she\'s mad.', 'grin'],
      ['kambree', 'I\'m gonna let that slide because you\'re six and I\'m a professional.', 'angry'],
      ['kay', 'Dr. Thaddeus Krill. Archaeologist. Seventy-eight. Somehow entered in the Birdman race.', 'smirk'],
    ] },
    { t: 'invest', title: 'AHU TONGARIKI', bg: 'easter', sites: [{ id: 'ahu', name: 'The Fifteen Moai', clues: [{ id: 'feather', x: .3, y: .8 }], jokes: [{ icon: 'map', x: .7, y: .85, who: 'kd', say: 'This map has a smiley face where the treasure is. Bad guys are bad at maps.' }] }] },
    { t: 'game', kind: 'rhythm', id: 'birdman', bg: 'easter', cast: ['kay', 'krill'], bpm: 96, n: 12, need: 7, glyph: '🌊', title: 'Birdman Swim', how: 'Krill is swimming to the islet with the "egg." Tap on the beat to stroke. Kambree is screaming encouragement and insults.', win: 'You beat a 78-year-old man in a swimming race. Honestly? Still counts. You grab the egg.', lose: 'He beat you. He\'s seventy-eight. Kambree is filming.' },
    { t: 'interro', id: 'krill' },
    { t: 'story', s: [{ on: ['kay', 'kambree', 'kd'] },
      ['n', 'Twenty years of payroll on a USB drive shaped like an egg. The Hogs didn\'t just lose. Somebody MADE them lose. Every fumble, every pick-six, every season my granddaddy cried into his chili. Bought and paid for.'],
      ['kambree', 'Twenty years? Dad threw a recliner through the window in 2011. A RECLINER, Kay.', 'angry'],
      ['kay', 'Somebody owes Dad a recliner.', 'angry'],
      ['kd', 'And a window!', 'grin'],
    ] },
    { t: 'board', qs: [{ q: 'Where does the payroll go next?', opts: ['To the Count in Monaco', 'To Gigi', 'Back to La Paz', 'To a moai savings account'], a: 0, yes: 'Monaco. But the money takes the scenic route: Krill says it\'s washed through saffron in Marrakech first.' }] },
    { t: 'flight', from: 'IPC · Rapa Nui', q: 'Brock\'s wire went to "Saffron Queen Imports." Where?', dest: 'MARRAKECH', opts: [{ code: 'RAK', city: 'Marrakech, Morocco', ok: 1 }, { code: 'DXB', city: 'Dubai', no: 'Kambree: "I would LOVE Dubai. Wrong though. Pay attention, nerd."' }, { code: 'IST', city: 'Istanbul', no: 'Close-ish in spice terms. Wrong in every other term.' }] },
  ] });
