/* ===================== CHAPTERS 7-12 ===================== */
CH.push({ id: 'marrakech', n: 7, title: 'Spice Spice Baby', city: 'Marrakech, Morocco', bg: 'marrakech', music: 'travel', party: { kd: 1, cocoa: 1, kambree: 1 }, tag: 'Snake charmers. Saffron. Somebody\'s washing money in the spice.',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'kambree', 'kd'], bg: 'marrakech' },
      ['n', 'Jemaa el-Fnaa at sunset: orange-juice stalls, storytellers, smoke from a hundred grills, and one woman selling saffron at prices that should be illegal. Turns out they were.'],
      ['kd', 'Mommy! That man has a SNAKE in a BASKET!', 'grin'],
      ['kambree', 'Cool. Don\'t touch it. If it bites you, I\'m not sucking out the venom. That\'s a mom job.', 'angry'],
      ['kay', 'Zohra, the Saffron Queen. Let\'s go haggle.', 'smirk'],
    ] },
    { t: 'invest', title: 'THE SOUK', bg: 'marrakech', sites: [{ id: 'stall', name: 'Saffron Stall', icon: '🌺', hours: 2, clues: [{ id: 'saffron', x: .7, y: .72 }] }, { id: 'pawn', name: '"PawnHub" Stall', icon: '🦺', hours: 1, clues: [], jokes: [{ icon: 'card', x: .5, y: .7, who: 'kambree', say: 'A store called PawnHub. I\'m buying something here just so I can say I did.' }] }], need: 1 },
    { t: 'story', s: [{ on: ['kay', 'kambree'] },
      ['kambree', 'Kay. This guy sells Kevlar vests next to a dusty Hello Kitty lunchbox. Fifteen hundred dollars.', 'smile'],
      { prompt: 'The vest:', who: 'n', choice: [{ t: 'BUY THE VEST ($1,500)', cash: -1500, set: { vest: 1 }, then: [['kay', 'Wear it. Every day. I mean it.', 'neutral'], ['kambree', 'Ugh. Fine. It\'s ugly. I\'m bedazzling it.', 'angry']] }, { t: 'HAGGLE (KAMBREE TRADES HER CAT STICKERS)', set: { vest: 1 }, then: [['kambree', 'Fine! Take my limited-edition Mochi Meow stickers! You\'re a monster! ...I have nine more sheets at home.', 'angry'], ['kay', 'Wear it. Every day. I mean it.', 'neutral']] }] },
    ] },
    { t: 'interro', id: 'zohra' },
    { t: 'story', s: [{ on: ['kay', 'kambree'] }, ['*', 'On a rooftop across the square: a snout hat. A gimbal. A wave.'], ['kay', 'Chad?! What the hell is HogWildChad doing in Marrakech?', 'shock'], ['kambree', 'Content. Probably. Get him.', 'angry'] ] },
    { t: 'game', kind: 'chase', id: 'rooftops', vehicle: 'foot', bg: 'marrakech', road: '#c8784a', side: '#8a4a2a', stripe: '#f2c89a', obs: ['crate', 'goat', 'barrel'], dur: 26, target: 'CHAD', targetV: 'foot', targetCol: '#ff6a3a', title: 'Rooftop Chase', how: 'Leap rugs, carpets, satellite dishes and one confused goat. Tap LEFT/RIGHT.', win: 'You corner him. "I\'m a CONTENT CREATOR," Chad yells, and jumps into a carpet shop. When you get there, he\'s gone. Who IS this guy?', lose: 'He gets away. A goat headbutts you. KD is not here to see it, thank God.' },
    { t: 'board', qs: [{ q: 'Who buys all of Zohra\'s saffron?', opts: ['The Count\'s yacht "The Point Spread"', 'Gigi', 'A Little Rock Applebee\'s', 'Dr. Krill'], a: 0, yes: 'Monaco. The yacht. And a keycard to get on it.' }] },
    { t: 'story', s: [{ on: ['kay', 'kambree', 'kd'] },
      ['kay', 'Monaco\'s a yacht full of killers. Tbilisi\'s a feast full of drunks. KD and Cocoa are not coming to either one.', 'neutral'],
      ['kambree', 'And I get pulled for "mandatory sensitivity training." In Quantico. Again. They say I made a hostage negotiator cry.', 'angry'],
      ['kay', 'You did make him cry.', 'smirk'],
      ['kambree', 'He cried FIRST. I just finished the thought.', 'angry'],
      ['kay', 'Layover at XNA. We\'re going to Gigi\'s.', 'smile'],
      { party: { kambree: 0 } },
    ] },
    { t: 'gigi', mode: 'drop' },
    { t: 'flight', from: 'XNA · Layover', q: 'The yacht keycard says "The Point Spread." Where does that yacht live?', dest: 'MONACO', opts: [{ code: 'NCE', city: 'Nice → Monaco', ok: 1 }, { code: 'CDG', city: 'Paris', no: 'Paris is romantic. You are not here for romance. You are here for revenge.' }, { code: 'LAS', city: 'Las Vegas', no: 'Wrong kind of casino. Right kind of tacky.' }] },
  ] });

CH.push({ id: 'monaco', n: 8, title: 'Sink or Swim', city: 'Monte Carlo, Monaco', bg: 'monaco', music: 'noir', party: { kd: 0, cocoa: 0, kambree: 0 }, solo: 1, tag: 'Two square kilometers. Forty thousand millionaires. One body in a hot tub.',
  steps: [
    { t: 'story', s: [{ on: ['kay'], bg: 'monaco' },
      ['n', 'Monaco. Smaller than Central Park, richer than God. Yachts stacked in the harbor like bathtub toys. I flashed a stolen keycard and walked onto The Point Spread like I owned it. Nobody stops a woman in a trench coat who looks annoyed.'],
      { card: { kind: 'text', from: 'KAMBREE 🎀', text: 'sensitivity training update: the instructor asked me to "name my feelings." i named them all after ex boyfriends. anyway u better not die on a boat w/o me. call me if u see the pig hat', h: 200 } },
      ['*', 'The hot tub on the top deck is bubbling. It shouldn\'t be bubbling red.'],
    ] },
    { t: 'invest', crime: 'sandy', title: 'CRIME SCENE: THE HOT TUB', bg: 'yacht', sites: [{ id: 'deck', name: 'Crime Scene · Top Deck', clues: [{ id: 'golfball', x: .25, y: .82 }, { id: 'yachttape', x: .82, y: .55 }, { id: 'chadsticker', x: .55, y: .9 }] }],
      autopsy: V('Sandy McFeeley, 34, the Count\'s golf pro and a Vauclair Talent "consultant." Beaten with a seven-iron (the club is at the bottom of the tub), then held under while the jets ran. The heat cooked him: skin sloughing off the hands in gloves, eyes clouded like poached eggs. Two broken fingers where he grabbed the edge. Water temperature: 104°F. The killer left the jets on. Like soup.', 'Sandy McFeeley, 34, the Count\'s golf pro. He was struck and then drowned in the hot tub. Two broken fingers suggest he fought back.') },
    { t: 'story', s: [{ on: ['kay'] },
      ['n', 'Somebody\'s cleaning up behind me. Every witness I find, somebody finds first. And they leave a sticker. Smash that subscribe.'],
      ['*', 'Below the stern, a huge man in a Hawaiian shirt unties the yacht\'s tender. He looks up at me, says nothing, and putters off into the dark.'],
      ['kay', 'Crew board by the gangway: "TENDER: T. DOBBINS." Six-foot-seven of nobody-asked. Crab Daddy said a big guy in a Hawaiian shirt drove Ringo\'s body in. Same guy? Filing that.', 'neutral'],
      ['*', 'Down on the pier, a silver-haired man in a velvet blazer jumps into a golf cart and floors it.'],
      ['kay', 'Count de Vauclair, you are NOT getting away in a golf cart. That\'s embarrassing for both of us.', 'angry'],
    ] },
    { t: 'game', kind: 'chase', id: 'golfcart', vehicle: 'cart', bg: 'monaco', road: '#4a4a52', side: '#2a6a3a', stripe: '#f4f0e6', obs: ['car', 'cone', 'barrel'], dur: 28, target: 'THE COUNT', targetV: 'cart', targetCol: '#c87ad0', title: 'Grand Prix Golf Cart Chase', how: 'Through the hairpins, the tunnel and a very angry Ferrari. Tap LEFT/RIGHT.', win: 'The Count\'s cart dies at the casino steps. "The battery," he sighs. "Like my third marriage."', lose: 'You hit a fountain. The Count waves from the casino roulette table.' },
    { t: 'interro', id: 'count' },
    { t: 'board', qs: [{ q: 'Who is cleaning up the witnesses?', opts: ['The Count', 'A man in a pig-snout hat', 'Sandy', 'Monaco\'s yacht valet'], a: 1, yes: 'The pig hat. The stickers. The camera. ...No. It can\'t be.' }, { q: 'Where does the Spread\'s money move next?', opts: ['Tbilisi: Zurab the Banker\'s feast', 'Back to Easter Island', 'Gigi\'s savings account', 'Paris'], a: 0 }] },
    { t: 'flight', from: 'NCE · Nice', q: 'The Banker, Zurab, hides codes in his toasts. Where is the feast?', dest: 'TBILISI', opts: [{ code: 'TBS', city: 'Tbilisi, Georgia', ok: 1 }, { code: 'ATL', city: 'Atlanta, Georgia', no: 'Wrong Georgia. The peach one. Classic.' }, { code: 'ATH', city: 'Athens', no: 'Lovely ruins. Wrong ruin.' }] },
  ] });

CH.push({ id: 'tbilisi', n: 9, title: 'Ninety-Nine Toasts', city: 'Tbilisi, Georgia', bg: 'tbilisi', music: 'dance', party: { kd: 0, cocoa: 0, kambree: 0 }, solo: 1, tag: 'Wine is 8,000 years old here. So are some of the toasts.',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'zurab'], bg: 'tbilisi' },
      ['n', 'Tbilisi. Balconies hanging over the river like they\'re eavesdropping. Sulfur baths under brick domes. And a supra: a feast so long that the table has its own zip code. The tamada runs the table. Tonight the tamada was the Spread\'s banker.'],
      ['zurab', 'A guest! An American! Sit! Drink! You will toast with me, or you will insult my grandmother!', 'grin'],
      ['kay', 'I\'d never insult your grandmother. I just met you, and I already want to insult you.', 'smirk'],
      ['zurab', 'HAH! I like her! Toast-off! If you are still standing, I answer one question!', 'grin'],
    ] },
    { t: 'game', kind: 'rhythm', id: 'toastoff', bg: 'tbilisi', cast: ['kay', 'zurab'], bpm: 108, n: 14, need: 8, glyph: '🍷', title: 'The Toast-Off', how: 'Tap on the beat to raise your glass, drink, toast, and DON\'T fall over. Listen for the codes.', win: 'Zurab slides under the table mid-toast, still talking. You catch every word of the last one.', lose: 'The room spins. You toasted a lamp. Zurab weeps with joy. You still caught the last toast... barely.', item: 'chacha' },
    { t: 'invest', title: 'THE SUPRA TABLE', bg: 'tbilisi', sites: [{ id: 'table', name: 'The Feast', clues: [{ id: 'toast', x: .3, y: .78 }, { id: 'winelabel', x: .72, y: .7 }], jokes: [{ icon: 'cigar', x: .55, y: .88, who: 'kay', say: 'A cheese boat the size of a canoe. KD would\'ve climbed in it.' }] }] },
    { t: 'story', s: [{ on: ['kay'] }, ['n', '"Two brothers who share one liver, one desk and one pen." I\'ve listened to four hundred hours of true crime. I know a clue when it gets drunk and hits on me.'], ['*', 'Zurab bolts for the sulfur baths.'], ['kay', 'Oh, come ON. Who runs into a BATH?', 'angry'] ] },
    { t: 'interro', id: 'zurab' },
    { t: 'story', s: [{ on: ['kay'] },
      ['n', 'Conjoined twin forgers in Siem Reap, the city whose name is usually translated "Siam defeated." The universe was writing my podcast for me.'],
      ['*', 'A text arrives. A photo of an accountant in Reykjavik named Bjarki, holding a sign: "I WANT OUT. MEET ME."'],
      ['kay', 'Reykjavik. But first... I\'m getting my baby back.', 'smile'],
    ] },
    { t: 'gigi', mode: 'pick' },
    { t: 'story', s: [{ on: ['kay', 'kambree', 'kd'], bg: 'gigi' }, { party: { kambree: 1 } }, ['kambree', 'I\'m BACK, bitches. Sensitivity training is done. I\'m so sensitive now. I\'m sensitive to how stupid everybody is.', 'angry'], ['kd', 'Aunt Kambree said a jar word!', 'grin'], ['kambree', 'Put it on my tab, little man. I\'ve got a long tab.', 'smirk'] ] },
    { t: 'flight', from: 'XNA', q: 'The accountant wants out. Where is Bjarki?', dest: 'REYKJAVIK', opts: [{ code: 'KEF', city: 'Reykjavik, Iceland', ok: 1 }, { code: 'OSL', city: 'Oslo', no: 'Kambree: "Oslo? You\'re thinking of Svalbard. Which we\'ll get to. Unfortunately."' }, { code: 'DUB', city: 'Dublin', no: 'Wrong island. Right weather.' }] },
  ] });

CH.push({ id: 'reykjavik', n: 10, title: 'Fermented', city: 'Reykjavik, Iceland', bg: 'reykjavik', music: 'noir', party: { kd: 1, cocoa: 1, kambree: 1 }, tag: 'Geothermal pools, northern lights, and a man boiled like a hot dog.',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'kambree', 'kd'], bg: 'reykjavik' },
      ['n', 'Reykjavik. A church shaped like a rocket. Hot dogs that locals swear are the best on Earth. And a hot pot steaming at dawn with Bjarki the accountant in it, very much not wanting out anymore.'],
      ['kay', 'Kambree. Take KD and Cocoa to the hot dog stand. Now. Two dogs each. Extra crunchy onions.', 'neutral'],
      ['kambree', 'Got it. C\'mon, little man. Let\'s go eat our feelings.', 'neutral'],
      ['kd', 'Can Cocoa have one with everything?', 'grin'],
      { on: ['kay'], party: { kd: 0, cocoa: 0 } },
      ['n', 'Kambree took KD out of view. Then she came back alone, leaving him with the hot dog lady, Sigga, who has six grandkids and the forearms of a crab fisherman. Good. Some things a six-year-old shouldn\'t see.'],
      { on: ['kay', 'kambree'] },
    ] },
    { t: 'invest', crime: 'bjarki', title: 'CRIME SCENE: THE HOT POT', bg: 'reykjavik', sites: [{ id: 'pot', name: 'Crime Scene · Hot Pot', clues: [{ id: 'bjarkiglasses', x: .22, y: .85 }, { id: 'chadsticker', x: .8, y: .82 }] }],
      autopsy: V('Bjarki Thorvaldsson, 41. Zip-tied at the wrists and ankles, then lowered into a geothermal vent channel diverted into the pot: water near 190°F. He was alive when he went in; the scalding is worst on the soles of the feet, where he tried to stand. The skin of his face has slipped like a wet paper bag. The double-pig coin was placed on his tongue. His glasses were found ten feet away, lens etched from the inside.', 'Bjarki Thorvaldsson, 41. Bound and left in the scalding geothermal water. The double-pig coin was found with him. His glasses were found ten feet away, etched from the inside.') },
    { t: 'story', s: [{ on: ['kay', 'kambree'] },
      ['kambree', '"The Cleaner has a camera." Kay. Camera. Pig hat. Stickers everywhere we go. It\'s the YouTube idiot.', 'angry'],
      ['kay', 'We need proof. Tonight we stake out the harbor. Somebody\'s meeting the Cleaner at the ferry.', 'neutral'],
      { party: { kd: 1, cocoa: 1 }, on: ['kay', 'kambree', 'kd'] },
      ['*', 'That night: a rental car, three adults\' worth of hot dogs, one six-year-old, one dog, and the northern lights dancing green over the harbor.'],
      ['kd', 'Mommy, the windows are all foggy because Cocoa tooted.', 'grin'],
      ['kambree', 'That wasn\'t Cocoa. That was me. I\'m not sorry. Wipe the window, nerd.', 'smirk'],
    ] },
    { t: 'game', kind: 'fog', id: 'stakeout', bg: 'reykjavik', sus: ['bjarki', 'krill', 'chad', 'sandy', 'brock'], ans: 2, order: [3, 0, 2, 4, 1], time: 26, clue: 'Wipe the fog. Tap the one wearing the red hog scarf.', title: 'Foggy Stakeout', how: 'Swipe to wipe the windshield, then tap the person in the RED HOG SCARF before they board the ferry.', win: 'It\'s HIM. HogWildChad. Boarding a ferry, talking to his own camera. KD gasps: "Mommy, that\'s THE AIR MAN!"', lose: 'Too foggy. The ferry leaves. But KD saw something...' },
    { t: 'story', s: [{ on: ['kay', 'kambree', 'kd'] },
      ['kd', 'The air man! From the airplane! He sat behind us on the way to Argentina. He has a piggy on his arm with two heads.', 'grin'],
      ['kay', 'Baby, can you draw it for me?', 'smile'],
      ['kd', 'I\'m a great drawer. I got a sticker for drawing.', 'grin'],
      { clue: 'drawing' },
      ['kambree', 'That\'s... that\'s actually perfect. The kid\'s a better witness than every adult on this continent.', 'smile'],
      ['kay', 'Svalbard. Bjarki\'s last email said the master ledger is in an old coal mine near the seed vault. KD and Cocoa go to Gigi\'s. No arguments.', 'neutral'],
      ['kd', 'Can I bring Gigi a hot dog?', 'grin'],
      ['kambree', 'Bring her three. She\'ll pretend she doesn\'t want them.', 'smile'],
    ] },
    { t: 'gigi', mode: 'drop' },
    { t: 'flight', from: 'XNA · Layover', q: 'The ledger is in a mine by the seed vault. Where?', dest: 'SVALBARD', opts: [{ code: 'LYR', city: 'Longyearbyen, Svalbard', ok: 1 }, { code: 'ANC', city: 'Anchorage', no: 'Cold. Wrong. Kambree buys a moose hat anyway.' }, { code: 'GOH', city: 'Nuuk, Greenland', no: 'Gorgeous. Not a seed vault in sight.' }] },
  ] });

CH.push({ id: 'svalbard', n: 11, title: 'Nobody Dies in Longyearbyen', city: 'Longyearbyen, Svalbard', bg: 'svalbard', music: 'interro', party: { kd: 0, cocoa: 0, kambree: 1 }, solo: 1, tag: 'More polar bears than people. Technically, nobody can be buried here.',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'kambree'], bg: 'svalbard' },
      ['n', 'Svalbard. Three hundred miles past the edge of Norway. Signs warn you about polar bears like other towns warn you about deer. You can\'t be buried here: the permafrost won\'t let the dead decay.'],
      ['kambree', 'So nobody\'s allowed to die here? Great. Then nobody\'s allowed to shoot me. Put that in the brochure.', 'angry'],
      ['kay', 'You wearing the vest?', 'neutral'],
      { if: 'vest', then: [['kambree', 'Yes, MOM. I bedazzled it. It says "SHOOT ME, I DARE YOU" in rhinestones.', 'smirk']], else: [['kambree', 'Obviously. Bought it myself. Rhinestones. Don\'t ask.', 'smirk']] },
      { set: { vest: 1 } },
    ] },
    { t: 'invest', title: 'MINE No. 3', bg: 'mine', sites: [{ id: 'mine', name: 'The Abandoned Mine', clues: [{ id: 'ledger', x: .5, y: .78 }], jokes: [{ icon: 'bottle', x: .2, y: .85, who: 'kambree', say: 'A box labeled "SEEDS: OZARK HOGWASH BARLEY." Subtle. Real subtle.' }] }] },
    { t: 'story', s: [{ on: ['kay', 'kambree'], music: 'tension' },
      ['n', 'Twenty years of payoffs. Every page initialed "B.P." The Commissioner. I didn\'t want to know who that was yet. My stomach already did.'],
      { on: ['kay', 'chad', 'kambree'] },
      ['chad', 'What\'s up, Hog Nation! Special episode! "Finding Out Your Biggest Fan Is Also Your Biggest Problem."', 'grin'],
      ['kay', 'Chad. You killed Ringo.', 'angry'],
      ['chad', 'I CLEANED Ringo. Big difference. Content-wise. Now give me the ledger, Kayleigh, or the baby sister gets edited out.', 'grin'],
      ['kambree', 'Edit THIS, you snout-hat bitch.', 'angry'],
      { sfx: 'gun', shake: 16, flash: '#fff' },
      ['*', 'BANG. Kambree spins and drops.'],
      ['kay', 'KAMBREE!', 'shock'],
      ['chad', 'Smash that subscribe!', 'grin'],
      { on: ['kay', 'kambree'] },
      ['*', 'Kayleigh drops to her knees. Kambree gasps, and claws at her rhinestone vest. A flattened slug is stuck dead center.'],
      ['kambree', 'OW. OW. Mother... that... HURT. Is my vest okay? Are my rhinestones okay?!', 'angry'],
      ['kay', 'You\'re alive. You\'re ALIVE. I\'m gonna kill you.', 'grin'],
      ['kambree', 'Get. Him. Kay. Go. I\'ll be here. Lying on the ground. Being pretty.', 'angry'],
    ] },
    { t: 'game', kind: 'chase', id: 'snowmobile', vehicle: 'sled', bg: 'svalbard', road: '#dfe8f2', side: '#f6f9fc', stripe: '#9ab0c8', obs: ['rock', 'crate', 'rock'], dur: 30, target: 'CHAD', targetV: 'sled', targetCol: '#ff6a3a', title: 'Snowmobile Chase', how: 'Chase Chad across the glacier. Dodge rocks and supply crates. Tap LEFT/RIGHT.', win: 'You clip his sled. He tumbles into a snowbank and loses half the ledger... and then a helicopter hauls him away on a rope ladder. Rich-people escape. Of course.', lose: 'You lose him in a whiteout. But you still have half the ledger.' },
    { t: 'story', s: [{ on: ['kay', 'kambree'] },
      ['kambree', 'He took half the ledger. The other half says who\'s paying him. "B.P." Who do we know with those initials, Kay?', 'angry'],
      ['kay', 'Let\'s not say it out loud until we can prove it.', 'neutral'],
      ['*', 'Chad\'s snowmobile is nose-down in a drift where he bailed for the rope ladder. Something is flapping under the windshield.'],
      { clue: 'manifest' },
      ['kay', 'A charter manifest. Helicopter to Tromsø, then a cargo jet straight to Zanzibar. One crate: "FRAGILE. JERSEY #7 + PAPERS."', 'shock'],
      ['kambree', 'Ringo\'s jersey? That sick bastard took a trophy off a dead kid. Him, the jersey and our half of the ledger, all flying to the equator. Why the hell ZANZIBAR?', 'angry'],
      ['kay', 'Look who signs for it at the other end: "T. DOBBINS, dhow SNAPPER, Stone Town harbor." Chad doesn\'t keep evidence. He hands it to the boat guy, and the boat guy sinks it in the Indian Ocean.', 'neutral'],
      { card: { kind: 'dossier', who: 'tank', title: 'FBI FILE: THEODORE "TANK" DOBBINS', text: 'Age 38. 6\'7". Long snapper, Arkansas, 2009-2014: 412 snaps, zero bad ones. Undrafted. Opened a sports bar called Snap Daddy\'s. It went under in 11 months.\n\nNow: "TRANSPORT" in the Spread\'s books. If cash, evidence or a body has to vanish, it goes on his boat. Ushuaia: the crab boat. Monaco: the yacht tender. Zanzibar: the dhow SNAPPER.\n\nNo violent record. Texts his mother in Pine Bluff every night.', h: 430 } },
      ['kambree', 'TANK DOBBINS? The long snapper? Gigi has his rookie card on the fridge. She calls him "the only Hog who never fumbled."', 'shock'],
      ['kay', 'He drove Ringo\'s body to the crab tank, Kambree. He untied the Count\'s boat the night Sandy died. He\'s been at every handoff for years.', 'angry'],
      ['kambree', 'So he\'s the Spread\'s delivery boy. And delivery boys see EVERYTHING. Who signs, who pays, who\'s on top.', 'smug'],
      ['kay', 'And he\'s not a killer. He\'s a scared man with a boat. Get him away from Chad and he\'ll talk.', 'neutral'],
      ['kambree', 'Then we beat that crate to Zanzibar. Go get your kid. I\'m gonna sit in the car and ice my boobs.', 'angry'],
    ] },
    { t: 'board', qs: [{ q: 'Where are Ringo\'s jersey and the ledger half going?', opts: ['Zanzibar: Tank Dobbins\'s dhow in Stone Town', 'Back to the Count in Monaco', 'Staying in Tromsø', 'Gigi\'s house'], a: 0, yes: 'The manifest: cargo jet to ZNZ, signed for by T. Dobbins, dhow SNAPPER. Chad hands off, and Tank makes it disappear by sea.' }, { q: 'Why does Tank Dobbins matter?', opts: ['He\'s the Spread\'s transport. He\'s been at every handoff and can name the boss', 'He\'s the Commissioner', 'He killed Ringo himself', 'He sells crabs'], a: 0, yes: 'The crab boat. The yacht tender. The dhow. He drives, he sees, and he\'s scared. That\'s a witness.' }] },
    { t: 'gigi', mode: 'pick' },
    { t: 'flight', from: 'XNA', q: 'The manifest: Chad\'s crate lands at ZNZ and is signed for by T. Dobbins, dhow SNAPPER, Stone Town harbor. Where to?', dest: 'ZANZIBAR', opts: [{ code: 'ZNZ', city: 'Zanzibar, Tanzania', ok: 1 }, { code: 'MLE', city: 'Maldives', no: 'Kambree: "Honeymoon destination. We are not on a honeymoon. Get it together."' }, { code: 'CPT', city: 'Cape Town', no: 'Close-ish continent. Wrong coast.' }] },
  ] });

CH.push({ id: 'zanzibar', n: 12, title: 'Spice World', city: 'Stone Town, Zanzibar', bg: 'zanzibar', music: 'travel', party: { kd: 1, cocoa: 1, kambree: 1 }, tag: 'Giant tortoises. Carved doors. A tracker hiding in plain sight.',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'kambree', 'kd', 'cocoa'], bg: 'zanzibar' },
      ['n', 'Zanzibar. Stone Town\'s carved wooden doors, spice markets and dhows with sails like folded napkins. KD wanted to see the giant tortoises on Prison Island. Cocoa wanted the keychain. She\'d wanted it for weeks.'],
      ['kd', 'Cocoa! No! That\'s my Hog keychain from Mister Ice Cream Suit!', 'grin'],
      ['*', 'CRUNCH. The keychain cracks open. A tiny circuit board blinks green.'],
      ['kambree', 'That\'s a GPS tracker. Kay. That\'s been in your kid\'s backpack since XNA.', 'angry'],
      ['kay', 'Bo Pettigrew gave KD that keychain.', 'shock'],
      { clue: 'tracker' },
      { prompt: 'The tracker:', who: 'n', choice: [{ t: 'SMASH IT', set: { tracker: 'smash' }, then: [['kambree', 'With pleasure.', 'grin'], { sfx: 'crash', shake: 8 }, ['kambree', 'Oops. Smashed. Sorry, Grandpa Murder.', 'smirk']] }, { t: 'TURN IT (MAIL IT TO ANTARCTICA)', set: { tracker: 'turn' }, then: [['kay', 'Let\'s mail it to a research station in Antarctica. Let him track a penguin for a while.', 'smirk'], ['kd', 'Send it to Angry Gary!', 'grin']] }] },
      ['kd', 'Mommy, is Mister Ice Cream Suit a bad guy?', 'grin'],
      ['kay', 'Maybe, baby. But don\'t you worry. Mommy\'s handling it. Go feed the tortoise a hibiscus.', 'smile'],
    ] },
    { t: 'invest', title: 'STONE TOWN DOCKS', bg: 'zanzibar', sites: [{ id: 'dock', name: 'The Dhow Harbor', clues: [{ id: 'tankphoto', x: .7, y: .78 }], jokes: [{ icon: 'cash', x: .3, y: .85, who: 'kambree', say: 'A tip jar for a tortoise. I respect the hustle.' }] }] },
    { t: 'story', s: [{ on: ['kay', 'kambree', 'tank'], bg: 'zanzibar' },
      ['*', 'At the end of the pier: a dhow with SNAPPER painted on the bow. On deck, six-foot-seven of Hawaiian shirt is prying open a crate stenciled "FRAGILE."'],
      ['kay', 'Tank Dobbins. Arkansas long snapper, 2009 to 2014. Four hundred twelve snaps. Zero bad ones.', 'neutral'],
      ['tank', '...You know my snap count? Ma\'am, NOBODY knows my snap count.', 'scared'],
      ['kambree', 'Our mom does. She also has your rookie card on her fridge, and you just broke her heart, you big dumb boat.', 'angry'],
      ['tank', 'I just drive, ma\'am. Chad said drop the crate past the reef. I didn\'t open it. I don\'t open things.', 'sad'],
      ['*', 'He looks at the jersey sticking out of the crate. Then he cuts the line and SNAPPER lurches away from the pier.'],
      ['kambree', 'He\'s RUNNING. On a BOAT. Kay, steal that other boat. I\'m driving.', 'angry'],
    ] },
    { t: 'game', kind: 'chase', id: 'dhow', vehicle: 'boat', bg: 'zanzibar', road: '#2a8ab8', side: '#1a6a98', stripe: '#9ae0f8', obs: ['wave', 'barrel', 'crate'], dur: 28, target: 'TANK', targetV: 'boat', targetCol: '#2ab0d8', title: 'Dhow Chase', how: 'Tank\'s escaping by dhow! Kambree is steering (badly). Tap LEFT/RIGHT to dodge waves and floating crates.', win: 'Tank\'s dhow runs aground on a sandbar. He sits down in the water and sighs like a man who\'s been waiting to get caught.', lose: 'Your sail tears. Tank waves. Kambree steals a jet ski.' },
    { t: 'interro', id: 'tank' },
    { t: 'board', qs: [{ q: 'Who killed Ringo, Tito, Sandy and Bjarki?', opts: ['Tank Dobbins', 'HogWildChad, the Cleaner', 'Dr. Krill', 'The Count'], a: 1, yes: 'Chad. Tank drove the boat. Chad did the cleaning. KD\'s drawing proves it.' }, { q: 'Who forged the fake NIL contracts?', opts: ['The Hawke twins in Siem Reap', 'Zohra', 'Coach Barlow', 'Gigi'], a: 0 }] },
    { t: 'flight', from: 'ZNZ · Zanzibar', q: 'Zurab\'s toast: "two brothers who share one liver." The forgers live in the city whose name is usually translated "Siam defeated." Where?', dest: 'SIEM REAP', opts: [{ code: 'REP', city: 'Siem Reap, Cambodia', ok: 1 }, { code: 'BKK', city: 'Bangkok', no: 'Kambree: "Siam IS Thailand, genius. The name says Siam DEFEATED. Think."' }, { code: 'HAN', city: 'Hanoi', no: 'Wrong country. Delicious noodles though.' }] },
  ] });
