/* ===================== CHAPTERS 13-16 + ENDING ===================== */
CH.push({ id: 'siemreap', n: 13, title: 'Siam Defeated', city: 'Siem Reap, Cambodia', bg: 'siemreap', music: 'travel', party: { kd: 1, cocoa: 1, kambree: 1 }, tag: 'Sunrise over Angkor Wat. Two professors. One spleen.',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'kambree', 'kd'], bg: 'siemreap' },
      ['n', 'Angkor Wat at sunrise: five lotus towers turning pink over the reflecting pool, a thousand phones held up like candles. Somewhere off Pub Street, two forgers were sharing a desk, a pen, and a whole lot more.'],
      ['kd', 'Mommy, the temple is upside down in the water!', 'grin'],
      ['kay', 'That\'s a reflection, baby. Like you and me.', 'smile'],
      ['kambree', 'Or like me and you, Kay. Joined at the hip. Like Siamese twins.', 'smirk'],
      ['kay', 'Except I\'m the pretty one.', 'grin'],
      ['kambree', 'And I\'m the one with the gun. Every time. It never gets old.', 'grin'],
      { on: ['kay', 'hawke'] },
      ['hawke', 'WENDELL: Good morning. WINSTON: We\'ve been expecting you. WENDELL: We have NOT. WINSTON: I have. I read her podcast reviews.', 'smug'],
      ['kay', 'Professors Hawke. Conjoined twin forgers. My podcast listeners are going to lose their minds.', 'grin'],
    ] },
    { t: 'board', title: 'THE TWIN PARADOX', qs: [{ q: 'One twin ALWAYS lies. One ALWAYS tells the truth. Wendell: "Winston would say the orders came from Monaco." Winston: "The orders came from Arkansas." Where did the orders really come from?', opts: ['Monaco', 'Arkansas', 'Macau', 'Tbilisi'], a: 1, yes: 'If Winston lied, Wendell would be the truthful one, but Winston didn\'t say Monaco. So Winston\'s honest. Arkansas. Somebody back home.', no: 'Kambree: "Logic puzzles make me want to commit crimes. Try again."' }] },
    { t: 'interro', id: 'hawke' },
    { t: 'story', s: [{ on: ['kay', 'kambree'] }, ['*', 'The twins hop into a tuk-tuk. Both of them. Sideways. They make it look easy.'], ['kambree', 'They\'re RUNNING? They have three legs between them!', 'angry'], ['kay', 'And a head start. Go!', 'angry'] ] },
    { t: 'game', kind: 'chase', id: 'tuktuk', vehicle: 'tuktuk', bg: 'siemreap', road: '#c8884a', side: '#3a7a3a', stripe: '#f2c89a', obs: ['cow', 'crate', 'cone'], dur: 26, target: 'THE TWINS', targetV: 'tuktuk', targetCol: '#c8a070', title: 'Tuk-Tuk Chase', how: 'Through Ta Prohm\'s tree roots and down to the floating villages. Tap LEFT/RIGHT to dodge cows and fruit carts.', win: 'The twins\' tuk-tuk gets stuck between two banyan roots. "WENDELL: This is your fault. WINSTON: It\'s OUR fault, that\'s how this works."', lose: 'A cow blocks the road. The cow does not care about your case.' },
    { t: 'flight', from: 'REP · Siem Reap', q: 'The twins say the Bookmaker records everyone. Where is Madame Lau?', dest: 'MACAU', opts: [{ code: 'MFM', city: 'Macau', ok: 1 }, { code: 'HKG', city: 'Hong Kong', no: 'So close. A ferry ride. Six hours of your life in a ferry line.' }, { code: 'SIN', city: 'Singapore', no: 'Clean, gorgeous, wrong.' }] },
  ] });

CH.push({ id: 'macau', n: 14, title: 'The House Always Wins', city: 'Macau', bg: 'macau', music: 'interro', party: { kd: 1, cocoa: 1, kambree: 1 }, tag: 'Neon, egg tarts, and a 233-meter interrogation.',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'kambree', 'kd'], bg: 'macau' },
      ['n', 'Macau. Neon casinos taller than God\'s patience, Portuguese tiles on the old streets, and egg tarts so good that KD ate fourteen and then asked if he could live here.'],
      ['kd', 'Can we live here? I\'ll get a job. I\'ll be an egg tart tester.', 'grin'],
      { item: 'eggtarts' },
      ['kambree', 'Little man, you\'re hired. Now go with Cocoa and the hotel lady and watch the fountain show. Mommy and I are going to dangle a lady off a tower.', 'grin'],
      { party: { kd: 0, cocoa: 0 }, on: ['kay', 'lau'] },
      ['*', 'The Macau Tower bungee platform. 233 meters up. Wind howling. Madame Jade Lau, harnessed in, smiling like the wind works for her.'],
      ['lau', 'Agent. You came all this way to see me jump?', 'smug'],
      ['kay', 'I came all this way to see if you\'d talk before or after.', 'smirk'],
    ] },
    { t: 'interro', id: 'lau' },
    { t: 'story', s: [{ on: ['kay', 'kambree', 'lau'] },
      ['lau', 'The recording. The Commissioner, in his own sweet voice. In exchange, I walk away. Do we have a deal?', 'smug'],
      { prompt: 'Lau\'s deal:', who: 'n', choice: [{ t: 'TAKE THE DEAL', set: { lauDeal: 1 }, then: [['kay', 'Deal. Give me the tape.', 'neutral'], ['lau', 'Pleasure doing business. The house always wins.', 'smug'], ['kambree', 'I hate this. I hate her. I love her shoes. I hate this.', 'angry']] }, { t: 'FAKE IT, THEN ARREST HER', set: { lauDeal: 0, lauBusted: 1 }, then: [['kay', 'Deal.', 'smile'], ['lau', 'Pleasure doing busi—', 'smug'], ['kambree', 'Madame Lau, you are under arrest. Also I\'m taking your shoes into evidence. Forever.', 'grin'], ['lau', 'You... cheated.', 'angry'], ['kay', 'The house always wins. Today, I\'m the house.', 'grin']] }] },
      { clue: 'lautape' },
      { card: { kind: 'note', title: 'TRANSCRIPT · LAU TAPE #88', text: 'VOICE (sweet, Southern): "That boy Ringo won\'t play ball, darlin\'. Twenty years, and one kid with a conscience is gonna ruin it. Have Chad clean it up. Make it look like a kidnappin\'. Folks love a kidnappin\'."', font: 'type', px: 15, h: 260 } },
      ['kambree', 'That\'s him. That\'s Grandpa Catfish. Bo freaking Pettigrew.', 'angry'],
      ['kay', 'Proof first. He\'s meeting the Board in Mongolia for Naadam. We take him there.', 'neutral'],
      ['kay', 'Which means... XNA. Gigi\'s. Again.', 'smile'],
      { party: { kd: 1, cocoa: 1 } },
    ] },
    { t: 'gigi', mode: 'drop' },
    { t: 'flight', from: 'XNA · Layover', q: 'The Board meets at a ger camp during Naadam. Where?', dest: 'ULAANBAATAR', opts: [{ code: 'UBN', city: 'Ulaanbaatar, Mongolia', ok: 1 }, { code: 'ALA', city: 'Almaty', no: 'Mountains, yes. Naadam, no.' }, { code: 'PEK', city: 'Beijing', no: 'Kambree: "Next door. Wrong door."' }] },
  ] });

CH.push({ id: 'ulaanbaatar', n: 15, title: 'Naadam Good', city: 'Ulaanbaatar, Mongolia', bg: 'ulaanbaatar', music: 'chase', party: { kd: 0, cocoa: 0, kambree: 1 }, solo: 1, tag: 'Wrestling, horses, archery. And a cane that isn\'t a cane.',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'kambree'], bg: 'ulaanbaatar' },
      ['n', 'Naadam. The "three games of men": wrestling, horse racing, archery. Except the archery\'s got women and the horse racing\'s got kids and the wrestling\'s got one man the size of a parked car: Batzorig, the Golden Eagle. Guarding a fancy ger camp full of very rich, very guilty people.'],
      ['kambree', 'Kay, I\'m gonna say something and you\'re not gonna like it. Wrestle him.', 'smirk'],
      ['kay', 'WHAT.', 'shock'],
      ['kambree', 'It\'s Naadam. Respect gets you through the door. Also, I wanna see it. I\'ve wanted to see it since I was nine.', 'grin'],
    ] },
    { t: 'game', kind: 'rhythm', id: 'bokh', bg: 'ulaanbaatar', cast: ['kay', 'batzorig'], bpm: 104, n: 14, need: 8, glyph: '🦅', title: 'Bökh Wrestling', how: 'Grip, shift, throw. Tap on the beat. Don\'t let any part of you but your feet touch the ground.', win: 'You hook his leg and he goes down like a felled tree. The crowd roars. Batzorig does the eagle dance... for YOU.', lose: 'He wins, gently. Then he does the eagle dance anyway and invites you to dinner. Respect earned.' },
    { t: 'interro', id: 'batzorig' },
    { t: 'story', s: [{ on: ['kay', 'kambree'] }, ['kay', 'Midnight. The ger camp. The Board\'s inside.', 'neutral'], ['kambree', 'I\'m wearing the vest. I\'m wearing TWO vests. I\'m a vest sandwich. Let\'s go.', 'angry'] ] },
    { t: 'game', kind: 'shot', id: 'raid', bg: 'ulaanbaatar', tgtId: 'zurab', decoy: 1, decoyId: 'brock', ammo: 7, need: 3, coverCol: '#a8743c', title: 'The Ger Camp Raid', how: 'Board members pop up behind the gers. Tap FIRE when the red reticle is on a bad guy. Don\'t shoot the "civilian" (it\'s Brock, as a waiter, somehow).', win: 'Zurab, the Count and a pile of bodyguards are face-down in the grass. Kambree is sitting on the Count. In the chaos, a white-suited old man runs for a helicopter. He drops his cane.', lose: 'You\'re pinned down. Kambree flanks them screaming the lyrics to a Hello Kitty theme song she made up. It works.' },
    { t: 'story', s: [{ on: ['kay', 'kambree'] },
      ['*', 'The hog-head cane lies in the grass. The head has twisted off. Inside: a tiny chamber, a spent shell, and the smell of gunpowder.'],
      { clue: 'cane' },
      { on: ['kay', 'pettigrew', 'kambree'] },
      ['pettigrew', '(from the helicopter, bullhorn) Darlin\', you were never supposed to be this GOOD. See y\'all at Homecoming!', 'smile'],
      ['kay', 'Bo Pettigrew. The Commissioner. He paid for my whole trip so he could watch me through my baby\'s keychain.', 'angry'],
      ['kambree', 'Twenty years of making Gigi cry into her chili. He\'s DEAD, Kay. Legally. Like, arrested-dead.', 'angry'],
      ['kay', 'Homecoming. He\'ll be in his suite. And Chad knows he\'s about to be the fall guy.', 'neutral'],
    ] },
    { t: 'flight', from: 'UBN · Ulaanbaatar', q: 'Pettigrew said "See y\'all at Homecoming." Where?', dest: 'FAYETTEVILLE', opts: [{ code: 'XNA', city: 'Fayetteville, Arkansas', ok: 1 }, { code: 'LIT', city: 'Little Rock', no: 'Kambree: "If you say Little Rock one more time I\'m pushing you out of the plane."' }, { code: 'MCO', city: 'Orlando', no: 'KD\'s still owed that vacation. But not now.' }] },
  ] });

CH.push({ id: 'homecoming', n: 16, title: 'Homecoming', city: 'Fayetteville, Arkansas · The Stadium', bg: 'stadium', music: 'tension', party: { kd: 0, cocoa: 0, kambree: 1 }, tag: 'Sold out. Down 31-0 at halftime. As usual... or not as usual?',
  steps: [
    { t: 'story', s: [{ on: ['kay', 'gigi', 'kambree'], bg: 'gigi', music: 'gigi' },
      ['gigi', 'KD\'s napping and Cocoa\'s in her vest. I\'ll bring them to the stadium after halftime, once you\'ve taken out the trash.', 'smile'],
      ['kay', 'Gigi, I love you.', 'grin'],
      ['gigi', 'I know, honey. Take a cookie. Kambree, take two, you look skinny and mean.', 'smile'],
      ['kambree', 'I AM skinny and mean. Thank you, Gigi.', 'smile'],
      { bg: 'stadium', on: ['kay', 'kambree'], music: 'tension' },
      ['n', 'Homecoming. Seventy-six thousand people calling the Hogs. Down 31 to nothing at halftime, because of course. And up in the luxury suite, a man in a white suit was about to tie up his last loose end.'],
      { sfx: 'gun', shake: 10 },
      ['kambree', 'That was a gunshot. In a suite. During the halftime band. Kay.', 'angry'],
    ] },
    { t: 'invest', crime: 'chad', title: 'CRIME SCENE: THE PETTIGREW SUITE', bg: 'suite', sites: [{ id: 'suite', name: 'Crime Scene · Luxury Suite 1', clues: [{ id: 'casing', x: .2, y: .85 }, { id: 'chadsticker', x: .78, y: .88 }] }],
      autopsy: V('Chad "HogWildChad" Bixby, 34. One .41-caliber round through the left eye at a range of about three feet; the exit wound took out a fist-sized piece of the back of his skull, and most of it is on the window, over the fifty-yard line. His camera was still recording. His last words, on tape: "Wait, wait, I\'ll do a sponsored..." The snout hat is somehow still on.', 'Chad Bixby, 34. A single shot from about three feet away. His camera was still recording. His last words: "Wait, wait, I\'ll do a sponsored..."') },
    { t: 'story', s: [{ on: ['kay', 'kambree'] },
      ['n', 'The Commissioner cleaned up his Cleaner. Separated the twins, you could say: the brains from the hands. Now it was my turn to stitch it all together.'],
      ['kambree', 'Building security is saying YOU did it, Kay. Pettigrew planted a story. Time to lay it out. All of it.', 'angry'],
    ] },
    { t: 'accuse' },
    { t: 'story', s: [{ on: ['kay', 'pettigrew', 'kambree'], bg: 'suite' },
      ['kay', 'Bo Pettigrew. You ran the Spread for twenty years. You bet against your own team and paid kids to lose. When Ringo said no, you had Chad kill him and dress it up as a kidnapping.', 'angry'],
      ['kay', 'You tracked me through my son\'s keychain. And today you shot your own Cleaner with the derringer in your cane. Your Siamese twin of crime. You cut him loose, and you don\'t even have the decency to be sad.', 'angry'],
      ['pettigrew', 'Darlin\'... it was a sure thing in an unsure world. Twenty years of guaranteed money. And one boy with a conscience was gonna ruin it for one lousy winning season.', 'smile'],
      ['kambree', 'One winning season? Do you know what that would\'ve MEANT to Gigi?! You absolute dried-up catfish turd!', 'angry'],
      ['*', 'Pettigrew grabs the team mascot, a big foam hog named Sooey Louie, by the snout, and runs for the field.'],
      ['kay', 'He took Sooey Louie! Kambree, he took the HOG!', 'shock'],
    ] },
    { t: 'game', kind: 'chase', id: 'field', vehicle: 'foot', bg: 'field', road: '#2a7a3a', side: '#1a5a2a', stripe: '#ffffff', obs: ['barrel', 'crate', 'cone'], dur: 26, target: 'PETTIGREW', targetV: 'foot', targetCol: '#f4f0e6', title: 'Halftime Chase', how: 'Through the marching band! Dodge tubas, the drumline and one baton twirler. Tap LEFT/RIGHT.', win: 'Fifty-yard line. The band freezes mid-note. Pettigrew spins around, Sooey Louie in a headlock, a second derringer in his hand.', lose: 'You took a tuba to the face. Kambree tackles a drummer by mistake. Pettigrew is at the 50.' },
    { t: 'game', kind: 'shot', id: 'standoff', bg: 'field', tgtId: 'pettigrew', ammo: 4, need: 1, cover: [[.5, .6]], coverKind: 'mascot', title: 'Standoff at the 50', how: 'He\'ll pop up from behind the mascot. One clean shot at the derringer. Tap FIRE when the reticle is on him.', win: 'CRACK. The derringer flies out of his hand. Sooey Louie body-slams him. 76,000 people call the Hogs.', lose: 'You missed, and Kambree throws her Mochi Meow keychain. It bonks him right between the eyes. Down he goes. Close enough.' },
    { t: 'ending' },
  ] });

const WRONG_HOG = [{ on: ['kay', 'kambree'], music: 'noir' },
  ['*', 'WRONG HOG. Pettigrew laughs all the way to his golf cart. Security handcuffs Kambree to a nacho machine. Sooey Louie files a complaint.'],
  ['kambree', 'Kay. KAY. That was the dumbest accusation in the history of this state, and this state has had some accusations.', 'angry'],
  ['kay', 'Okay, okay. Back to the board. Look at the proof again.', 'neutral'],
  { hours: -12 }];
const ENDING = [
  { on: ['kay', 'kambree'], bg: 'stadium', music: 'victory' },
  ['n', 'Second half. Biscuit Toombs, free of the Spread at last, threw four touchdowns. Every receiver had Ringo\'s #7 written on his wristband. The Hogs came back from 31 down. Seventy-six thousand people lost their voices. Back home, Gigi threw a recliner through the window. In a good way.'],
  { if: 'lauBusted', then: [['kambree', 'Lau\'s in custody. The Count\'s in custody. Zurab is in custody and he\'s still toasting. The twins asked for adjoining cells. Like, VERY adjoining.', 'grin']], else: [['kambree', 'Lau walked, but we got everybody else. The Count, Zurab, the twins. And Pettigrew\'s going away until the sun burns out.', 'smirk']] },
  { on: ['kay', 'gigi', 'kd', 'cocoa'], party: { kd: 1, cocoa: 1 } },
  ['gigi', 'We made it for the fourth quarter! I brought cookies for the whole section.', 'smile'],
  ['kd', 'MOMMY! The Hogs WON! And my swear jar is FULL!', 'grin'],
  { fn: () => { RT.jarTotal = 1000 + GS.swear * 37 + Math.round(GS.cash / 10); } },
  ['kay', 'How full, baby?', 'smile'],
  ['kd', 'It\'s SO full. Gigi counted. It\'s enough to fly Ringo\'s mama here for his jersey ceremony!', 'grin'],
  ['*', 'At the end of the game, Ringo Jones\' #7 is retired. His mama holds it up, and she\'s smiling through tears. The whole stadium calls the Hogs for him.'],
  { on: ['kay', 'kambree', 'kd'] },
  ['kambree', 'Bureau called. They want you full-time, Special Agent. I said you\'d take it on one condition.', 'smile'],
  ['kay', 'KD gets a badge too.', 'grin'],
  ['kambree', 'Already laminated. Junior Special Agent Kamden. He outranks me now. I\'ve never been prouder or more furious.', 'grin'],
  ['kd', 'I\'m a JUNIOR SPECIAL AGENT! Cocoa, you\'re my partner!', 'grin'],
  { toast: 'KD IS A JUNIOR SPECIAL AGENT', sfx: 'win' },
  ['kay', 'Joined at the hip like Siamese twins, except I\'m the pretty one.', 'grin'],
  ['kambree', 'And I\'m the one with the gun. Woo Pig, bitch.', 'grin'],
  ['kd', 'SWEAR JAR!', 'grin'],
  ['n', 'Case closed. Twenty years of losing, and one woman kept score. Woo Pig Justice.'],
];
const STING = [{ on: [], bg: 'stadium', music: 'noir' },
  { card: { kind: 'note', title: 'ONE SEASON LATER', text: 'Nobody is paying anybody. The Spread is gone. The Hogs are clean.\n\nThey go 2-10.\n\nCoach Duke Barlow, at the podium: "Turns out... some of that was just us."', font: 'type', px: 16, h: 280 } }];
